# Generated by Django 5.2.8 on 2026-01-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-date_registered'], 'verbose_name': 'Matériel', 'verbose_name_plural': 'Matériels'},
        ),
        migrations.AlterField(
            model_name='material',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='material',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('BON_ETAT', 'Bon état'), ('IN_USE', "En cours d'utilisation à l'atelier"), ('TAKEN_BACK', "Repris par l'apprenti"), ('LOST', 'Perdu'), ('DAMAGED', 'Endommagé'), ('HORS_SERVICE', 'Hors service')], default='BON_ETAT', max_length=20, verbose_name='État'),
        ),
    ]
