# Generated by Django 5.2.8 on 2026-01-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='couleur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='taille',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UNIQUE', 'Unique')], max_length=50, null=True),
        ),
    ]
