# Generated by Django 5.2.8 on 2025-12-31 13:19

import django.db.models.deletion
import django.utils.timezone
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, validators=[users.models.validate_phone])),
                ('photo_profil', models.CharField(default='/assets/images/profiles/default.png', max_length=255)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('APPRENTI', 'Apprenti'), ('WORKER', 'Worker'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], default='CLIENT', max_length=20)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('AUTHENTICATOR', 'Authenticator'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('two_factor_backup_codes', models.JSONField(default=list)),
                ('last_2fa_used', models.DateTimeField(blank=True, null=True)),
                ('password_history', models.JSONField(default=list)),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('account_enabled', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_user_agent', models.TextField(blank=True, null=True)),
                ('adresse_livraison', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_token_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_password_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Apprentice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('MAITRE', 'Maître')], default='DEBUTANT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apprentice_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apprentices',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fonction', models.CharField(blank=True, choices=[('COORDINATEUR', 'Coordinateur'), ('SUPERVISEUR', 'Superviseur'), ('TECHNICIEN', 'Technicien'), ('COMMERCIAL', 'Commercial'), ('SUPPORT', 'Support'), ('LOGISTIQUE', 'Logistique')], max_length=20, null=True)),
                ('groupe', models.CharField(blank=True, choices=[('PRODUCTION', 'Production'), ('QUALITE', 'Qualité'), ('LIVRAISON', 'Livraison'), ('SUPPORT', 'Support'), ('CREATION', 'Création')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workers',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_enabled'], name='users_account_c6979e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
    ]
