# Generated by Django 5.2.8 on 2026-01-10 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_workergroup_workerproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du matériel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('status', models.CharField(default='BON_ETAT', max_length=20, verbose_name='État')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'APPRENTI'}, on_delete=django.db.models.deletion.CASCADE, related_name='apprentice_materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
