# Generated by Django 5.2.8 on 2026-01-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
