# Generated by Django 4.2 on 2026-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_workertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='fonction',
            field=models.CharField(blank=True, choices=[('COORDINATEUR', 'Coordinateur'), ('SUPERVISEUR', 'Superviseur'), ('TECHNICIEN', 'Technicien'), ('COMMERCIAL', 'Commercial')], max_length=20, null=True),
        ),
    ]
