# Generated by Django 5.2.8 on 2025-12-31 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NelsiusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nelsius_transaction_id', models.CharField(max_length=100, unique=True)),
                ('merchant_reference', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('initiated', 'Initier'), ('processing', 'En traitement'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('payment_url', models.URLField(blank=True)),
                ('callback_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nelsius_transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Transaction Nelsius',
                'verbose_name_plural': 'Transactions Nelsius',
                'ordering': ['-created_at'],
            },
        ),
    ]
