# Generated by Django 5.2.8 on 2026-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_groupinvitation_dailyjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration de l'annonce", null=True),
        ),
    ]
