# Generated by Django 5.2.8 on 2026-01-10 02:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_announcement_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
