# Generated by Django 5.2.8 on 2026-01-22 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date de publication de l'annonce"),
        ),
    ]
