# Generated by Django 5.2.8 on 2026-01-24 22:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_announcement_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('DEFILE', 'Défilé de Mode'), ('SOUTENANCE', 'Soutenance Apprenti'), ('DON', 'Don Caritatif'), ('PARTENARIAT', 'Partenariat'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Image à la une')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'évènement")),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Évènement',
                'verbose_name_plural': 'Évènements',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
