# Generated by Django 5.2.8 on 2026-01-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Image à la une'),
        ),
    ]
