# Generated by Django 4.2 on 2026-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_shipping_cost_alter_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('processing', 'En traitement'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('cutting', 'En coupe'), ('sewing', 'En couture'), ('fitting', 'Passer essayer'), ('in_production', 'En confection'), ('ready', 'Prête'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
