# Generated by Django 5.2.8 on 2026-03-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='production_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('processing', 'En traitement'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('measurements_taken', 'Mesures prises'), ('cutting', 'En coupe'), ('sewing', 'En couture'), ('fitting', 'Passer essayer'), ('in_production', 'En confection'), ('ready', 'Couture terminée / Prête'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
